try {
  console.log(a);
} catch (error) {
  console.log("An error occurred:", error.message);
}
